// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me_slice: dynamic(() => import("./AboutMeSlice")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  subscription_my_blog: dynamic(() => import("./SubscriptionMyBlog")),
};
