// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me_slice: dynamic(() => import("./AboutMeSlice")),
  article_section: dynamic(() => import("./TextSection")),
  body: dynamic(() => import("./Body")),
  contact_me: dynamic(() => import("./ContactMe")),
  contact_with_me: dynamic(() => import("./ContactWithMe")),
  gallery: dynamic(() => import("./Gallery")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  subscription_my_blog: dynamic(() => import("./SubscriptionMyBlog")),
};
