// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me_slice: dynamic(() => import("./AboutMeSlice")),
  article_section: dynamic(() => import("./TextSection")),
  body: dynamic(() => import("./Body")),
  contact_with_me: dynamic(() => import("./ContactWithMe")),
  footer: dynamic(() => import("./Footer")),
  gallery: dynamic(() => import("./Gallery")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  my_personal_info: dynamic(() => import("./MyPersonalInfo")),
};
